# Generated by Django 5.0.6 on 2024-06-20 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_stok', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterGudang',
            fields=[
                ('kode_gudang', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('qty', models.IntegerField(default=0)),
                ('kode_barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_stok.masterstock')),
            ],
        ),
    ]
