# Generated by Django 5.0.6 on 2024-06-20 03:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_gudang', '0001_initial'),
        ('master_stok', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeProduct', models.CharField(default='', max_length=70)),
                ('tanggal_transaksi', models.DateField(default=datetime.date.today)),
                ('kode_transaksi', models.CharField(max_length=20, unique=True)),
                ('jumlah', models.IntegerField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kode_barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_stok.masterstock')),
                ('kode_gudang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_gudang.mastergudang')),
            ],
        ),
    ]
