# Generated by Django 5.0.6 on 2024-06-23 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='codeProduct',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='kode_transaksi',
        ),
    ]
