# Generated by Django 5.0.6 on 2024-06-23 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_customer', '0002_alter_mastercustomer_id'),
        ('transaction', '0002_remove_transaction_codeproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='id_customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='master_customer.mastercustomer'),
            preserve_default=False,
        ),
    ]
