# Generated by Django 5.0.6 on 2024-06-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastercustomer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
