# Generated by Django 5.0.6 on 2024-06-23 16:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_customer', '0002_alter_mastercustomer_id'),
        ('transaction', '0003_transaction_id_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_transaksi', models.DateField(default=datetime.date.today)),
                ('total_transaksi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sisa_saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_customer.mastercustomer')),
                ('id_transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction')),
            ],
        ),
    ]
