# Generated by Django 5.0.6 on 2024-06-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='id_transaksi',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='tanggal_transaksi',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='total_transaksi',
        ),
    ]
